--- #YAML:1.0
name:                Games-Ratings
version:             0.0.5
abstract:            generic methods for rating calculation (e.g. chess ratings)
license:             ~
author:              
    - Christian Bartolomaeus <bartolin@gmx.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Std::Utils:             0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
